name: Django CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SECRET_KEY: test
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: test
      DB_NAME: test

    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: python manage.py test --settings api.test_settings
